### ISSUE TITLE
Fatal error when activating plugin if not using a Genesis theme

### ISSUE THREAD

**Issue by nickcernis** [copyblogger/genesis-simple-faq#25]
I stumbled upon an issue today that I think is worth fixing before we release this.

I see this fatal error when activating the plugin with Twenty Seventeen active:

~~~
[10-Aug-2017 16:46:51 UTC] PHP Fatal error:  Uncaught Error: Class 'Genesis_Simple_FAQ_Widget' not found in /Users/nick/Sync/Work/wp/wptest/wp-includes/class-wp-widget-factory.php:106
Stack trace:
#0 /Users/nick/Sync/Work/wp/wptest/wp-includes/widgets.php(113): WP_Widget_Factory->register('Genesis_Simple_...')
#1 /Users/nick/Sync/Work/wp/wptest/wp-content/plugins/genesis-simple-faq/genesis-simple-faq.php(186): register_widget('Genesis_Simple_...')
#2 /Users/nick/Sync/Work/wp/wptest/wp-includes/class-wp-hook.php(298): Genesis_Simple_FAQ->register_widgets('')
#3 /Users/nick/Sync/Work/wp/wptest/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
#4 /Users/nick/Sync/Work/wp/wptest/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#5 /Users/nick/Sync/Work/wp/wptest/wp-includes/widgets.php(1484): do_action('widgets_init')
#6 /Users/nick/Sync/Work/wp/wptest/wp-includes/class-wp-hook.php(298): wp_widgets_init('')
#7 /Users/nick/Sync/Work/wp/wptest/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array)
#8 /Users/nick/Sync/ in /Users/nick/Sync/Work/wp/wptest/wp-includes/class-wp-widget-factory.php on line 106
~~~

The error remains until you rename the genesis-simple-faq plugin folder, effectively locking users out of the admin area and front end.

Binding `instantiate` to `genesis_setup` in `genesis-simple-faq.php` seems to be the issue:

`add_action( 'genesis_setup', array( $this, 'instantiate' ) );`

We should probably include the Simple FAQ classes as long as the plugin is active, and not depend on Genesis being active too, because a user may switch to a non-Genesis theme after using the plugin:

`add_action( 'widgets_init', array( $this, 'instantiate' ) );`

That allows activation with a non-Genesis theme but also shows the notice: “Genesis Simple FAQ requires WordPress 4.8 and Genesis 2.5, or greater. Please install and activate the latest version of Genesis to use this plugin.”

Noting there does not seem to be anything in the plugin at the moment that makes it specific to Genesis; it works with other themes. (I understand that we plan to add FAQ styling to StudioPress themes, though, which might warrant the warning about it being Genesis-only.)

**Comment by nickcernis** [comment]
Looks good! Confirmed as working.
